name: Build Lix
on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v26
      - name: Cache the build
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Clone Lix
        uses: actions/checkout@v4
        with:
          repository: lix-project/lix
          ref: main
      - name: Build Lix (x86_64)
        run: |
          set -x
          cross_build() {
            nix-build --verbose \
              --expr 'with import (builtins.getFlake (toString ./.)).inputs.nixpkgs {
                        crossSystem.config = "'$1'";
                      };
                      callPackage ./package.nix {
                        pegtl = callPackage ./misc/pegtl.nix {};
                      }'
          }

          declare -A result
          result[x86_64-linux]=$(nix-build --verbose --attr packages.x86_64-linux.default)
          result[aarch64-linux]=$(cross_build aarch64-linux)

          cd "${TMPDIR:?}"
          tempBinCache=$(mktemp -d nixCache.XXXXXX)
          for target in "${!result[@]}"; do
            path=${result[$target]}
            printf '%s = %s\n' "$target" "$path" >> "$tempBinCache/.lix-paths"
            nix copy --no-check-sigs --to "file://$PWD/$tempBinCache" "$path"
          done

          tar --create --preserve-permissions --file=lix.tar "$tempBinCache"
          echo TARBALL="$PWD/lix.tar" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ env.TARBALL }}
          if-no-files-found: error
